version: "1.0"
services:
  postgres:
    image: postgres:15
    container_name: readmate-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: ghcr.io/michal-sternik/readmate-backend:latest
    container_name: readmate-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_IN: ${JWT_EXPIRE_IN}
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY}
      NODE_ENV: ${NODE_ENV}
      
  
  frontend:
    image: ghcr.io/michal-sternik/readmate-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /srv/app/ssl:/etc/nginx/ssl:ro

volumes:
  db_data:
