services:
  postgres:
    image: postgres:15
    container_name: readmate-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'

  # api:
  #   build: .
  #   container_name: nestjs-readmate-api
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   environment:
  #     - DB_HOST=postgres
