name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./readmate-backend -t ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }}
            
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push image to GHCR
      run: docker push ghcr.io/${{ github.repository_owner }}/my-app:${{ github.sha }}
