name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'readmate-backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'readmate-backend/**'
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env:
        IMAGE: ghcr.io/${{ github.repository_owner }}/readmate-backend
      run:
        TIMESTAMP = $(date +'%Y%m%d%H%M%S')
        docker build \
          -t $IMAGE:${TIMESTAMP} \
          -t $IMAGE:latest \
          ./readmate-backend
            
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
        
    - name: Push image to GHCR
      run: 
         docker push $IMAGE:${TIMESTAMP}
         docker push $IMAGE:latest
