name: Frontend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'readmate-frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'readmate-frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        env:
          TIMESTAMP: $(date +'%Y%m%d%H%M%S')
          IMAGE: ghcr.io/${{ github.repository_owner }}/readmate-frontend
        run: docker build ./readmate-frontend \
          -t $IMAGE:${TIMESTAMP} \
          -t $IMAGE:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push image to GHCR
        run: docker push $IMAGE:${TIMESTAMP}
             docker push $IMAGE:latest
