name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'readmate-backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'readmate-backend/**'
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set IMAGE and TIMESTAMP envs
      run: |
        echo "IMAGE=ghcr.io/${{ github.repository_owner }}/readmate-backend" >> $GITHUB_ENV
        echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV


    - name: Build the Docker image
      run: |
        docker build ./readmate-backend \
          -t $IMAGE:$TIMESTAMP \
          -t $IMAGE:latest
            
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
        
    - name: Push image to GHCR
      run: 
         docker push $IMAGE:${TIMESTAMP}
         docker push $IMAGE:latest
